#
# Copyright 2019-2023 Nestybox, Inc.
#

#
# Docker image for deploying Sysbox-CE on a K3s host.
#
# Build with:
#
# docker build -t ghcr.io/nestybox/sysbox-deploy-k3s .
# China mirror alternative:
# docker build --build-arg BASE_IMAGE=docker.cnb.cool/i0358/docker-images-chrom/centos-centos:stream9 -t docker.cnb.cool/i0358/docker-images-chrom/sysbox-deploy-k3s .
#

# Note: we use a centos base image because it carries a systemctl that can
# communicate with the host's systemd via dbus. This does not work when using a
# ubuntu + systemd image (systemctl can't not connect to the host's dbus, even
# though the host's dbus socket was mounted into the container).

ARG BASE_IMAGE=docker.cnb.cool/i0358/docker-images-chrom/centos-centos:stream9
FROM ${BASE_IMAGE}

ARG sys_arch
ENV SYS_ARCH=${sys_arch}
ARG sysbox_version
ENV SYSBOX_VERSION=${sysbox_version}

ARG DEST=/opt/sysbox
ARG KUBECTL_VERSION="1.32.13"
ARG CRICTL_VERSION="v1.35.0"
ARG GITHUB_PROXY="https://gh-proxy.org/"

RUN dnf install -y --allowerasing systemd curl wget git bc which jq procps-ng rsync fuse3 \
    && dnf clean all

RUN case "${SYS_ARCH}" in \
        amd64|arm64) kubectl_arch="${SYS_ARCH}" ;; \
        *) echo "unsupported kubectl arch: ${SYS_ARCH}" && exit 1 ;; \
    esac \
    && curl -Lso /bin/kubectl https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/${kubectl_arch}/kubectl \
    && chmod +x /bin/kubectl

# China mirror alternative for kubectl RPM:
# RUN yum install -y https://mirrors.aliyun.com/kubernetes-new/core/stable/v1.32/rpm/${kubectl_arch}/kubectl-${KUBECTL_VERSION}-150500.1.1.${kubectl_arch}.rpm

RUN wget "${GITHUB_PROXY}https://github.com/TomWright/dasel/releases/download/v1.27.3/dasel_linux_${SYS_ARCH}" \
    && mv dasel_linux_${SYS_ARCH} dasel && chmod +x dasel && mv ./dasel /usr/local/bin/dasel

# crictl will be copied to the host, and used by the runtime installation agents.
RUN wget "${GITHUB_PROXY}https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-${SYS_ARCH}.tar.gz" \
    && tar zxvf crictl-${CRICTL_VERSION}-linux-${SYS_ARCH}.tar.gz -C /usr/local/bin \
    && chmod +x /usr/local/bin/crictl \
    && rm -f crictl-${CRICTL_VERSION}-linux-${SYS_ARCH}.tar.gz

# shiftfs-dkms sources
RUN git clone --branch k5.4 "${GITHUB_PROXY}https://github.com/nestybox/shiftfs-dkms.git" /opt/shiftfs-k5.4 \
    && git clone --branch k5.10 "${GITHUB_PROXY}https://github.com/nestybox/shiftfs-dkms.git" /opt/shiftfs-k5.10 \
    && git clone --branch k5.11 "${GITHUB_PROXY}https://github.com/nestybox/shiftfs-dkms.git" /opt/shiftfs-k5.11 \
    && git clone --branch k5.13 "${GITHUB_PROXY}https://github.com/nestybox/shiftfs-dkms.git" /opt/shiftfs-k5.13 \
    && git clone --branch k5.16 "${GITHUB_PROXY}https://github.com/nestybox/shiftfs-dkms.git" /opt/shiftfs-k5.16 \
    && git clone --branch k5.17 "${GITHUB_PROXY}https://github.com/nestybox/shiftfs-dkms.git" /opt/shiftfs-k5.17 \
    && git clone --branch k5.18 "${GITHUB_PROXY}https://github.com/nestybox/shiftfs-dkms.git" /opt/shiftfs-k5.18 \
    && git clone --branch k6.1 "${GITHUB_PROXY}https://github.com/nestybox/shiftfs-dkms.git" /opt/shiftfs-k6.1

#
# Load Sysbox installation artifacts
#

COPY bin/sysbox-ce /opt/sysbox/bin

# The inner K3s launcher invokes rsync through the bundled Sysbox tool path.
RUN cp -a /usr/bin/rsync /opt/sysbox/bin/generic/rsync
RUN cp -a /usr/bin/fusermount3 /opt/sysbox/bin/generic/fusermount3

RUN ln -s /opt/sysbox/bin/generic/sysbox-admission /usr/local/bin/sysbox-admission

COPY systemd/50-sysbox-mod.conf /opt/sysbox/systemd/50-sysbox-mod.conf
COPY systemd/99-sysbox-sysctl.conf /opt/sysbox/systemd/99-sysbox-sysctl.conf
COPY systemd/sysbox-installer-helper.service /opt/sysbox/systemd/sysbox-installer-helper.service
COPY systemd/sysbox-removal-helper.service /opt/sysbox/systemd/sysbox-removal-helper.service
COPY systemd/sysbox-fs.service /opt/sysbox/systemd/sysbox-fs.service
COPY systemd/sysbox-mgr.service /opt/sysbox/systemd/sysbox-mgr.service
COPY systemd/sysbox-snapshotter.service /opt/sysbox/systemd/sysbox-snapshotter.service
COPY systemd/sysbox.service /opt/sysbox/systemd/sysbox.service

COPY scripts/sysbox-deploy-k8s.sh /opt/sysbox/scripts/sysbox-deploy-k8s.sh
COPY scripts/sysbox-inner-k3s.sh /opt/sysbox/scripts/sysbox-inner-k3s.sh
COPY scripts/sysbox-installer-helper.sh /opt/sysbox/scripts/sysbox-installer-helper.sh
COPY scripts/sysbox-removal-helper.sh /opt/sysbox/scripts/sysbox-removal-helper.sh
